config/routes.rb
Rails.application.routes.draw do
  resources :documents
  resources :pagos
  resources :pagadors
  resources :expenses
  resources :budgets
  resources :providers
  resources :projects
  resources :tasks
  resources :cobros
  resources :compradors
  resources :sales
  resources :participations
  resources :investments
  devise_for :users
  root to: "pages#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/investment.rb
class Investment < ApplicationRecord
  has_many :participations
  has_many :users, through: :participations
  has_many :sales
  has_many :tasks
  has_many :documents
  has_many :projects
  has_one_attached :photo
  has_one_attached :analisis
  has_many_attached :documentos

def rentabilidad
  unless self.precio_venta.nil? && self.precio_adquisicion.nil? && self.gastos.nil?
    gasto = self.precio_adquisicion + self.gastos
    beneficio = self.precio_venta - gasto
    return (beneficio / gasto) * 100
  else
    return 0
  end
end

def linked_location
  unless self.google_location.nil?
    self.google_location.split('"',3)[1]
  else
    "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d149433181.77292404!2d0!3d-17.41699292008704!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xa4b9967b3390754b%3A0x6e52be1f740f2075!2sAnt%C3%A1rtida!5e1!3m2!1ses!2ses!4v1674123239102!5m2!1ses!2ses"
  end
end


end

app/controllers/investments_controller.rb
class InvestmentsController < ApplicationController
  before_action :set_investment, only: %i[ show edit update destroy ]

  # GET /investments or /investments.json
  def index
    @investments = Investment.all
  end

  # GET /investments/1 or /investments/1.json
  def show
  end

  # GET /investments/new
  def new
    @investment = Investment.new
  end

  # GET /investments/1/edit
  def edit
  end

  # POST /investments or /investments.json
  def create
    @investment = Investment.new(investment_params)

    respond_to do |format|
      if @investment.save
        format.html { redirect_to investment_url(@investment), notice: "Investment was successfully created." }
        format.json { render :show, status: :created, location: @investment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @investment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /investments/1 or /investments/1.json
  def update
    respond_to do |format|
      if @investment.update(investment_params)
        format.html { redirect_to investment_url(@investment), notice: "Investment was successfully updated." }
        format.json { render :show, status: :ok, location: @investment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @investment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /investments/1 or /investments/1.json
  def destroy
    @investment.destroy

    respond_to do |format|
      format.html { redirect_to investments_url, notice: "Investment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_investment
      @investment = Investment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def investment_params
      params.require(:investment).permit(:direccion, :precio_venta, :precio_adquisicion, :gastos, :estado, :poblacion, :description, :photo, :analisis, :google_location, documentos: [])
    end
end

app/views/investments/_form.html.erb
<%= simple_form_for(@investment) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :direccion %>
    <%= f.input :poblacion %>
    <%= f.input :google_location %>
    <%= f.input :description %>
    <%= f.input :precio_venta %>
    <%= f.input :precio_adquisicion %>
    <%= f.input :gastos %>
    <%= f.input :estado, collection: ["En análisis","Abierto para inversiones","En proceso","Terminado"]%>
    <%= f.input :photo, as: :file %>
    <%= f.input :analisis, as: :file %>
    <%# <%= f.input :documentos, as: :file, input_html: { multiple: true } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/investments/edit.html.erb
<h1>Editing Investment</h1>

<%= render 'form', investment: @investment %>

<%= link_to 'Show', @investment %> |
<%= link_to 'Back', investments_path %>

app/views/investments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Investments</h1>

<table>
  <thead>
    <tr>
      <th>Direccion</th>
      <th>Precio venta</th>
      <th>Precio adquisicion</th>
      <th>Gastos</th>
      <th>Estado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @investments.each do |investment| %>
      <tr>
        <td><%= investment.direccion %></td>
        <td><%= investment.precio_venta %></td>
        <td><%= investment.precio_adquisicion %></td>
        <td><%= investment.gastos %></td>
        <td><%= investment.estado %></td>
        <td><%= link_to 'Show', investment %></td>
        <td><%= link_to 'Edit', edit_investment_path(investment) %></td>
        <td><%= link_to 'Destroy', investment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Investment', new_investment_path %>

app/views/investments/new.html.erb
<h1>New Investment</h1>

<%= render 'form', investment: @investment %>

<%= link_to 'Back', investments_path %>

app/views/investments/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
    <div class="tar">
      <%= link_to 'Editar oportunidad de inversión', edit_investment_path(@investment), :class => "btn btn-secondary text-white" %>
    </div>
  <%# Título %>
  <div>
    <h1 class=" h1 text-center"><%= @investment.poblacion %></h1>
    <h2 class="text-center"><%= @investment.description %></h2>
  </div>

  <%# Foto / Datos %>
  <div class="d-flex justify-content-between show_card_img">
    <%=cl_image_tag @investment.photo.key, height: 300, width: 400, crop: :fill  %>
    <div class="datos_in_photo" >
      <div style="margin:1em;">
      <h4>
        <strong>Direccion:</strong>
        <%= @investment.direccion %>, <%= @investment.poblacion %>
      </h4>
      <h4>
        <strong>Estado:</strong>
        <%= @investment.estado %>
      </h4>
      </div>
      <br>
      <h3 style="text-align: center;">Análisis económico</h3>
      <div class="d-flex">
        <div style="margin:1em;">
          <p>
            <strong>Venta:</strong>
            <%= @investment.precio_venta.to_i %>€
          </p>
          <p>
            <strong>Compra:</strong>
            <%= @investment.precio_adquisicion.to_i %>€
          </p>
        </div>
        <div style="margin:1em;">
          <p>
            <strong>Rentabilidad:</strong>
            <%= @investment.rentabilidad.to_i %>%
          </p>
          <p>
            <strong>Gastos:</strong>
            <%= @investment.gastos.to_i %>€
          </p>
        </div>
      </div>
    </div>
  </div>

  <iframe src=<%=@investment.linked_location%> width="100%" height="450" class="mapa" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>

  <%# Enlace de la hoja de analisis %>
  <% if @investment.analisis.attached? %>
    <div class = "text-center m-3 show_card p-3 mb-2 bg-success ">
      <%= link_to("Ficha análisis", cl_image_path("#{@investment.analisis.key}"), class: "link text-white", style: "font-size:25px;") %>
    </div>
  <% end %>

  <%# Documentos legales / Tareas %>
  <div class= "d-flex justify-content-around">
    <div class= "show_card">
      <div class="d-flex justify-content-between">
      <h2>Documentos legales</h2>
      <%= link_to "+", new_document_path, :class => "h2 link text-success" %>
      </div>
      <%if @investment.documents.exists? %>
      <ul>
        <%@investment.documents.each_with_index do |document| %>
          <li><%= link_to("#{document.nom}", cl_image_path("#{document.pdf.key}"), class:"link text-success") %></li>
        <% end %>
      </ul>
      <% else %>
        <p>No hay documentos guardados</p>
      <% end %>
    </div>
    <div class= "show_card">
      <div class="d-flex justify-content-between">
        <h2>Tareas a realizar</h2>
        <%= link_to '+', new_task_path, :class => "h2 link text-success" %>
      </div>
      <%if @investment.tasks.exists? %>
      <br>
      <ul>
        <%@investment.tasks.each do |task| %>
          <li><%= link_to 'o', task, method: :delete, data: { confirm: 'Seguro que quieres eliminar la tarea?' }, class: "text-danger link" %>  <%= task.data_limit %> - <%= task.nom %></li>
        <% end %>
      </ul>
      <% else %>
        <p>No hay tareas pendientes</p>
      <% end %>
    </div>
  </div>

  <%# Proyectos %>
  <div class="show_card">
      <div class="tar">
      <%= link_to '+', new_project_path, :class => "btn btn-success text-white" %>
      </div>
    <h2 class="text-center pb-5">Proyectos</h2>
    <% if @investment.projects.exists? %>
      <% @investment.projects.each do |project| %>
        <h3 class="text-center bg-secondary text-white"><%= project.nombre %>:</h3>
        <div class="d-flex justify-content-around">
          <div>
            <h4 class="text-center text-secondary">Presupuestos</h4>
              <% if project.budgets.exists? %>
                <table class="table table-hover">
                  <thead>
                    <tr>
                      <th scope="col">Nombre</th>
                      <th scope="col">Total</th>
                      <th scope="col">Proveedor</th>
                      <th scope="col">Archivo</th>
                    </tr>
                  </thead>
                  <tbody>
                  <%project.budgets.each do |budget| %>
                    <tr>
                      <th scope="row"><%= budget.nom %></th>
                      <td><%= budget.quantitat %>€</td>
                      <td><%= budget.provider.nom_comercial %></td>
                      <%if budget.document.attached? %>
                        <td><%= link_to("Doc", cl_image_path("#{budget.document.key}")) %></td>
                      <% else %>
                        <td>-</td>
                      <% end %>
                    </tr>
                  <% end %>
                  </tbody>
                </table>
              <% else %>
                <p>No hay presupuestos guardados</p>
              <% end %>

          </div>
          <div>
            <h4 class="text-center text-secondary">Facturas</h4>
               <% if project.expenses.exists? %>
                <table class="table table-hover">
                  <thead>
                    <tr>
                      <th scope="col">Fecha</th>
                      <th scope="col">Nombre</th>
                      <th scope="col">Total</th>
                      <th scope="col">Proveedor</th>
                      <th scope="col">Archivo</th>
                      <th scope="col">Pagado</th>
                    </tr>
                  </thead>
                  <tbody>
                  <%project.expenses.each do |expense| %>
                    <tr>
                      <th scope="row"><%=expense.fecha%></th>
                      <td><%= expense.nom %></td>
                      <td><%= expense.quantitat %>€</td>
                      <td><%= expense.provider.nom_comercial %></td>
                        <%if expense.document.attached? %>
                          <td><%= link_to("Doc", cl_image_path("#{expense.document.key}")) %></td>
                        <% else %>
                        <td>-</td>
                        <% end %>
                      <td><%= expense.x_pagado.to_i %>%</td>
                    </tr>
                  <% end %>
                  </tbody>
                </table>
              <% else %>
                <p>No hay facturas guardadas</p>
              <% end %>

          </div>
        </div>
        <br>
      <% end %>
    <% else %>
      <p>No hay proyectos iniciados</p>
    <% end %>
    <div class="d-flex justify-content-around">
      <%= link_to 'Nuevo presupuesto', new_budget_path, :class => "btn btn-secondary text-white" %>
      <%= link_to 'Nueva factura', new_expense_path, :class => "btn btn-secondary text-white" %>
    </div>
  </div>

  <%# Ventas %>
  <div class="show_card">
    <div class="tar">
      <%= link_to '+', new_sale_path, :class => "btn btn-success text-white" %>
    </div>
    <div>
    <h2 class="text-center">Ventas</h2>
    </div>
    <% if @investment.sales.exists? %>
    <br>
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">Fecha</th>
            <th scope="col">Descirpción</th>
            <th scope="col">€</th>
            <th scope="col">Documento</th>
            <th scope="col">% Cobrado</th>
          </tr>
        </thead>
        <tbody>
          <%@investment.sales.each do |sale| %>
            <tr>
              <th scope="row"><%=sale.fecha%></th>
              <td><%= sale.descripcio %></td>
              <td><%= sale.quantitat %>€</td>
              <%if sale.document.attached? %>
                <td><%= link_to("Doc", cl_image_path("#{sale.document.key}")) %></td>
              <% else %>
              <td>-</td>
              <% end %>
              <td><%= sale.x_cobrado.to_i %>%</td>
            <tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
    No hay ventas
    <% end %>
  </div>

    <%# Participacions %>
  <div class="show_card">
    <div class="tar">
      <%= link_to '+', new_participation_path, :class => "btn btn-success text-white" %>
    </div>
    <div>
    <h2 class="text-center">Participaciones</h2>
    </div>
    <% if @investment.participations.exists? %>
    <br>
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">Fecha</th>
            <th scope="col">€</th>
            <th scope="col">Inversor</th>
          </tr>
        </thead>
        <tbody>
          <%@investment.participations.each do |participation| %>
            <tr>
              <th scope="row"><%=participation.data%></th>
              <td><%= participation.quantitat_invertida %>€</td>
              <td><%= participation.user.email %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
    Nadie ha invertido aú
    <% end %>
  </div>

</div>