config/routes.rb
Rails.application.routes.draw do
  resources :documents
  resources :pagos
  resources :pagadors
  resources :expenses
  resources :budgets
  resources :providers
  resources :projects
  resources :tasks
  resources :cobros
  resources :compradors
  resources :sales
  resources :participations
  resources :investments
  devise_for :users
  root to: "pages#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/dd7x7bqya/image/upload/v1673948439/Captura_de_pantalla_2023-01-17_a_las_10.33.09_frmexo.png" %>
    <% end %>

    <%if current_user && current_user.admin == true %>
      <div>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Crear
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <div class="d-flex flex-row">
            <div>
              <%= link_to 'Nueva oportunidad de inversión', new_investment_path, class: "dropdown-item" %>
              <%= link_to 'Nueva participación', new_participation_path, class: "dropdown-item" %>
              <%= link_to 'Nueva venta', new_sale_path, class: "dropdown-item" %>
              <%= link_to 'Nuevo proyecto', new_project_path, class: "dropdown-item" %>
              <%= link_to 'Nuevo presupuesto', new_budget_path, class: "dropdown-item" %>
              <%= link_to 'Nueva factura', new_expense_path, class: "dropdown-item" %>
            </div>
            <div>
              <%= link_to 'Nueva tarea', new_task_path, class: "dropdown-item" %>
              <%= link_to 'Nuevo proveedor', new_provider_path, class: "dropdown-item" %>
              <%= link_to 'Nuevo pago', new_pago_path, class: "dropdown-item" %>
              <%= link_to 'Nuevo pagador', new_pagador_path, class: "dropdown-item" %>
              <%= link_to 'Nuevo cobro', new_cobro_path, class: "dropdown-item" %>
              <%= link_to 'Nuevo comprador', new_comprador_path, class: "dropdown-item" %>
              </div>
          </div>
          </div>
        </div>
      </div>
            <div>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Ver
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <div>
              <%= link_to 'Oportunidades de inversión', root_path, class: "dropdown-item" %>
              <%= link_to 'Tareas', tasks_path, class: "dropdown-item" %>
              <%= link_to 'Ventas', sales_path, class: "dropdown-item" %>
              <%= link_to 'Facturas', expenses_path, class: "dropdown-item" %>
              <%= link_to 'Proveedores', providers_path, class: "dropdown-item" %>
              <%= link_to 'Compradores', compradors_path, class: "dropdown-item" %>
            </div>
          </div>
        </div>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav me-auto">
          <% if user_signed_in? %>
            <li class="nav-item active" style="margin-right: 1em;">
              <%= current_user.email %>
            </li>
            <li class="nav-item active">
              <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>

    <% else %>
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav me-auto">
          <% if user_signed_in? %>
            <li class="nav-item active" style="margin-right: 1em;">
              <%= current_user.email %>
            </li>
            <li class="nav-item active">
              <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
</div>