config/routes.rb
Rails.application.routes.draw do
  resources :documents
  resources :pagos
  resources :pagadors
  resources :expenses
  resources :budgets
  resources :providers
  resources :projects
  resources :tasks
  resources :cobros
  resources :compradors
  resources :sales
  resources :participations
  resources :investments
  devise_for :users
  root to: "pages#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: %i[ show edit update destroy ]

  # GET /expenses or /expenses.json
  def index
    @expenses = Expense.all
  end

  # GET /expenses/1 or /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses or /expenses.json
  def create
    @expense = Expense.new(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to expense_url(@expense), notice: "Expense was successfully created." }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1 or /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to expense_url(@expense), notice: "Expense was successfully updated." }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1 or /expenses/1.json
  def destroy
    @expense.destroy

    respond_to do |format|
      format.html { redirect_to expenses_url, notice: "Expense was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def expense_params
      params.require(:expense).permit(:nom, :quantitat, :fecha, :project_id, :provider_id, :document)
    end
end

app/views/expenses/_form.html.erb
<%= simple_form_for(@expense) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :nom %>
    <%= f.input :quantitat %>
    <%= f.input :fecha %>
    <%= f.association :project, label_method: :nombre %>
    <%= f.association :provider, label_method: :nom_comercial %>
    <%= f.input :document, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing Expense</h1>

<%= render 'form', expense: @expense %>

<%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="d-flex justify-content-between">
    <h1 class="text-center">Facturas</h1>
    <%= link_to 'Nova factura', new_expense_path, class:"btn btn-success text-white" %>
  </div>
  <br>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Descripcio</th>
        <th>Quantitat</th>
        <th>Fecha</th>
        <th>Investment</th>
        <th>Proveïdor</th>
        <th>Document</th>
        <th scope="col">% Cobrado</th>

        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @expenses.each do |expense| %>
        <tr>
          <td><%= link_to "#{expense.nom}", expense_path(expense) %></td>
          <td><%= expense.quantitat %></td>
          <td><%= expense.fecha %></td>
          <td><%= link_to "#{expense.project.investment.poblacion} - #{expense.project.investment.direccion}", investment_path(expense.project.investment) %></td>
          <td><%= link_to "#{expense.provider.nom_comercial}", provider_path(expense.provider) %></td>
          <%if expense.document.attached? %>
            <td><%= link_to("Doc", cl_image_path("#{expense.document.key}")) %></td>
          <% else %>
            <td>-</td>
          <% end %>
          <td><%= expense.x_pagado.to_i %>%</td>
          <td><%= link_to 'x', expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/expenses/new.html.erb
<h1>New Expense</h1>

<%= render 'form', expense: @expense %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
    <div class="d-flex justify-content-between">
      <h1><%= @expense.nom %></h1>
      <%= link_to 'Edit', edit_expense_path(@expense), :class => "btn btn-success text-white" %>
    </div>
    <br>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Descripcion</th>
        <th scope="col">Proyecto</th>
        <th scope="col">€</th>
        <th scope="col">Fecha</th>
        <th scope="col">Inversión</th>
        <th scope="col">Proveedor</th>
        <th scope="col">Documento</th>
        <th scope="col">% Cobrado</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @expense.nom %></td>
        <td><%= @expense.project.nombre %></td>
        <td><%= @expense.quantitat %></td>
        <td><%= @expense.fecha %></td>
        <td><%= @expense.project.investment.poblacion%>-<%= @expense.project.investment.direccion%></td>
        <td><%= link_to "#{@expense.provider.nom_comercial}", provider_path(@expense.provider) %></td>
        <%if @expense.document.attached? %>
          <td><%= link_to("Doc", cl_image_path("#{@expense.document.key}")) %></td>
        <% else %>
          <td>-</td>
        <% end %>
        <td><%= @expense.x_pagado.to_i %>%</td>
      <tr>
    </tbody>
  </table>

  <%# ver los pagos %>
  <br>
  <br>
  <div class="container">
    <div class="d-flex justify-content-between">
      <h2 style= "color: gray;"> - Pagos</h2>
      <%= link_to '+', new_pago_path, :class => "btn btn-success text-white" %>
    </div>
    <%@expense.pagos.each do |pago| %>
      <table class="table table-dark table-sm table-hover">
        <thead>
          <tr>
            <th scope="col">Fecha</th>
            <th scope="col">€</th>
            <th scope="col">Pagador</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= link_to "#{pago.fecha}", edit_pago_path(pago) %></td>
            <td><%= pago.quantitat %></td>
            <td><%= link_to "#{pago.pagador.nombre}", edit_pagador_path(pago.pagador) %></td>
          <tr>
        </tbody>
      </table>
    </div>
  <% end %>

</div>