config/routes.rb
Rails.application.routes.draw do
  resources :documents
  resources :pagos
  resources :pagadors
  resources :expenses
  resources :budgets
  resources :providers
  resources :projects
  resources :tasks
  resources :cobros
  resources :compradors
  resources :sales
  resources :participations
  resources :investments
  devise_for :users
  root to: "pages#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :investment
  has_many :cobros
  has_many :compradors, through: :cobros
  has_one_attached :document

  def x_cobrado
    cobrado = 0
    self.cobros.each do |cobro|
      cobrado += cobro.quantitat
    end
    total = self.quantitat

    return (cobrado / total) * 100
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: %i[ show edit update destroy ]

  # GET /sales or /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1 or /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales or /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to sale_url(@sale), notice: "Sale was successfully created." }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1 or /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to sale_url(@sale), notice: "Sale was successfully updated." }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1 or /sales/1.json
  def destroy
    @sale.destroy

    respond_to do |format|
      format.html { redirect_to sales_url, notice: "Sale was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sale_params
      params.require(:sale).permit(:descripcio, :quantitat, :fecha, :investment_id, :document)
    end
end

app/views/sales/_form.html.erb
<%= simple_form_for(@sale) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :descripcio %>
    <%= f.input :quantitat %>
    <%= f.input :fecha %>
    <%= f.association :investment, label_method: :direccion %>
    <%= f.input :document, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="d-flex justify-content-between">
    <h1 class="text-center">Ventas</h1>
    <%= link_to 'Nova venta', new_sale_path, class:"btn btn-success text-white" %>
  </div>
  <br>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Descripcio</th>
        <th>Quantitat</th>
        <th>Fecha</th>
        <th>Investment</th>
        <th>Document</th>
        <th scope="col">% Cobrado</th>

        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @sales.each do |sale| %>
        <tr>
          <td><%= link_to "#{sale.descripcio}", sale_path(sale) %></td>
          <td><%= sale.quantitat %></td>
          <td><%= sale.fecha %></td>
          <td><%= link_to "#{sale.investment.poblacion} - #{sale.investment.direccion}", investment_path(sale.investment) %></td>
          <%if sale.document.attached? %>
            <td><%= link_to("Doc", cl_image_path("#{sale.document.key}")) %></td>
          <% else %>
            <td>-</td>
          <% end %>
          <td><%= sale.x_cobrado.to_i %>%</td>
          <td><%= link_to 'x', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
    <div class="d-flex justify-content-between">
      <h1><%= @sale.descripcio %></h1>
      <%= link_to 'Edit', edit_sale_path(@sale), :class => "btn btn-success text-white" %>
    </div>
    <br>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Descirpción</th>
        <th scope="col">€</th>
        <th scope="col">Fecha</th>
        <th scope="col">Inversión</th>
        <th scope="col">Documento</th>
        <th scope="col">% Cobrado</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @sale.descripcio %></td>
        <td><%= @sale.quantitat %></td>
        <td><%= @sale.fecha %></td>
        <td><%= @sale.investment.poblacion%>-<%= @sale.investment.direccion%></td>
        <%if @sale.document.attached? %>
          <td><%= link_to("Doc", cl_image_path("#{@sale.document.key}")) %></td>
        <% else %>
          <td>-</td>
        <% end %>
        <td><%= @sale.x_cobrado.to_i %>%</td>
      <tr>
    </tbody>
  </table>

  <%# ver los cobros %>
  <br>
  <br>
  <div class="container">
    <div class="d-flex justify-content-between">
      <h2 style= "color: gray;"> - Cobros</h2>
      <%= link_to '+', new_cobro_path, :class => "btn btn-success text-white" %>
    </div>
    <%@sale.cobros.each do |cobro| %>
      <table class="table table-dark table-sm table-hover">
        <thead>
          <tr>
            <th scope="col">Fecha</th>
            <th scope="col">€</th>
            <th scope="col">Comprador</th>
            <th scope="col">Contacto</th>
            <th scope="col">Mail</th>
            <th scope="col">Identidad</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= link_to "#{cobro.fecha}", edit_cobro_path(cobro) %></td>
            <td><%= cobro.quantitat %></td>
            <td><%= link_to "#{cobro.comprador.nombre}", edit_comprador_path(cobro.comprador) %></td>
            <td><%= cobro.comprador.contacto%></td>
            <td><%= cobro.comprador.mail %></td>
            <%if cobro.comprador.document.attached? %>
              <td><%= link_to("Doc", cl_image_path("#{cobro.comprador.document.key}")) %></td>
            <% else %>
              <td>-</td>
            <% end %>
          <tr>
        </tbody>
      </table>
    </div>
  <% end %>

</div>